import type { Metadata } from "next";
import ClientProviders from "@/providers";

// CSS Styles
import "../style/globals.css";
import "react-toastify/dist/ReactToastify.css";
import "@reach/dialog/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
